%define SYSCALL_READ            0
%define SYSCALL_WRITE           1
%define SYSCALL_OPEN            2
%define SYSCALL_CLOSE           3
%define SYSCALL_STAT            4
%define SYSCALL_FSTAT           5
%define SYSCALL_LSTAT           6
%define SYSCALL_POLL            7
%define SYSCALL_LSEEK           8
%define SYSCALL_MMAP            9
%define SYSCALL_MPROTECT        10
%define SYSCALL_MUNMAP          11
%define SYSCALL_BRK             12
%define SYSCALL_RT_SIGACTION    13
%define SYSCALL_RT_SIGPROCMASK  14
%define SYSCALL_RT_SIGRETURN    15
%define SYSCALL_IOCTL           16
%define SYSCALL_PREAD64         17
%define SYSCALL_PWRITE64        18
%define SYSCALL_READV           19
%define SYSCALL_WRITEV          20
%define SYSCALL_ACCESS          21
%define SYSCALL_PIPE            22
%define SYSCALL_SELECT          23
%define SYSCALL_SCHED_YIELD     24
%define SYSCALL_MREMAP          25
%define SYSCALL_MSYNC           26
%define SYSCALL_MINCORE         27
%define SYSCALL_MADVISE         28
%define SYSCALL_SHMGET          29
%define SYSCALL_SHMAT           30
%define SYSCALL_SHMCTL          31
%define SYSCALL_DUP             32
%define SYSCALL_DUP2            33
%define SYSCALL_PAUSE           34
%define SYSCALL_NANOSLEEP       35
%define SYSCALL_GETITIMER       36
%define SYSCALL_ALARM           37
%define SYSCALL_SETITIMER       38
%define SYSCALL_GETPID          39
%define SYSCALL_SENDSIG         40
%define SYSCALL_SENDFILE        41
%define SYSCALL_SOCKET          41
%define SYSCALL_CONNECT         42
%define SYSCALL_ACCEPT          43
%define SYSCALL_EXIT            60
%define SYSCALL_FORK            57
%define SYSCALL_VFORK           58
%define SYSCALL_EXECVE          59
%define SYSCALL_WAIT4           61
%define SYSCALL_KILL            62
%define SYSCALL_UNAME           63
%define SYSCALL_GETTIMEOFDAY    96
%define SYSCALL_CLOCK_GETTIME   228

